#pragma once

#define LINKEY_FACTORY_PARTITION_LABEL "factory_data"
#define LINKEY_FACTORY_NAMESPACE "linkey"
#define LINKEY_FACTORY_KEY_MQTT_PASSWORD "mqtt-password"
#define LINKEY_FACTORY_KEY_BLE_POP "ble-pop"
#define LINKEY_FACTORY_FALLBACK_MQTT_PASSWORD LINKEY_FACTORY_KEY_MQTT_PASSWORD
#define LINKEY_FACTORY_FALLBACK_BLE_POP "linkey-pop"
